04_django/webapp/blog/urls.py
# 목록보기
from django.urls import path, re_path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    # Example: /blog/
    path('', PostLV.as_view(), name='index'),
    # Example: /blog/post
    path('post/', PostLV.as_view(), name='index'),
    # 첫번째 매개변수 정규표현식이라함
    # 꺽새안에있는것은 경로변수라고한다.
    # -(대쉬)는 -
    # w는 워드를 말함. 알파벳 or 숫자
    # +는 한개 이상 나온다.
    # 즉, 공백 없이 글자 -로만 구성된다.
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),

    # Example: /blog/archive/
    # 아카이브를 두개 붙이는 이유는 위에 슬러그 때문에 겹쳐서 두개로 적어주는것
    path('archive/', PostAV.as_view(), name='post_archive'),
    # Example: /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    # Example: /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/tag/
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    # Example: /blog/search/
    path('search/', SearchFormView.as_view(), name='search'),

    # Example: /blog/add/
    path('add/', PostCreateView.as_view(), name="add"),
    # Example: /blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
    # Example: /blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),

    path('download/<int:id>', download, name="download"),
]

04_django/webapp/bookmark/urls.py
from django.urls import path

from bookmark.views import *

app_name = 'bookmark'  # 해당 애플리케이션의 네임스페이스명

urlpatterns = [
    # mysite urls에서 북마크 뒤에 북마크 urls가 경로가되는데 빈문자열음 그냥
    # 북마크 목록이 보이는 화면이고 뒤에 인트형식의 기본키가 값이오면(상세값) 그 목록
    # 에 대한 정보로 가는 주소가 된다

    # 클래스 기반
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),

    # Example: /bookmark/add/
    path('add/', BookmarkCreateView.as_view(), name="add"),
    # Example: /bookmark/change/
    path('change/', BookmarkChangeLV.as_view(), name="change"),
    # Example: /bookmark/99/update/
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name="update"),
    # Example: /bookmark/99/delete/
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name="delete"),

    # function-based views
    # path('bookmark/', index, name='index'),
    # path('bookmark/<int:pk>', detail, name='detail')
]

04_django/webapp/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
# from bookmark.views import index, detail
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    # 클래스 기반 뷰
    path('bookmark/', BookmarkLV.as_view(), name='index'),
    path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('tinymce/', include('tinymce.urls')),


    # 함수기반의 뷰
    # path('bookmark/', index, name='index'),
    # path('bookmark/<int:pk>', detail, name='detail'),
]

04_django/webapp/templates/base.html
{%load static %}
<!--커뮤니티 버전이 장고를 지원하지 않기떄문에 빨간줄 무시해도됨-->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">
{% include 'menu.html' %}
<div class="container">
    {% block content%}{% endblock %}
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js">
</script>
{% block extra-script %}{% endblock %}
</html>

04_django/webapp/templates/base2.html
{%load static%}
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .jumbotron {
            background-image: url("{%static 'images/여신.png'%}");
            background-size: 100%
        }

    </style>
     {% block extra-style %}{% endblock %}
</head>

<body>
<div class="container">

    <div class="jumbotron mb-0 pt-4">
        <h1><font color="white"><i class="fas fa-home"></i> Bootstrap Tutorial</font>></h1>
        <font color="white"><p>Bootstrap is the most popular HTML, CSS...</p></font>
    </div>
    {% include 'menu.html' %}
    <div class="content">
        {% block content%}{% endblock %}
    </div>



</div>

{% block extra-script %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

</body>

</html>

04_django/webapp/templates/home.html
{% extends "base2.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<h1 class="my-5"><i class="fas fa-blog"></i>오늘의 포스트</h1>
{% include "post_list.html" %}

{% endblock %}

04_django/webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
 <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">
 Django</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-warning" href="{% url 'home' %}"><i class="fas fa-home"></i> Home</a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-warning"
                   href="{% url 'bookmark:index' %}"><i class="far fa-bookmark"></i> Bookmark</a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-warning"
                   href="{% url 'blog:index' %}"><i class="fas fa-blog"></i> Blog</a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-warning" href=""><i class="far fa-image"></i> Photo</a></li>
            <li class="nav-item dropdown mx-1 btn btn-light">
                <a class="nav-link dropdown-toggle text-warning" href="#"
                   data-toggle="dropdown"><i class="fas fa-user-cog"></i> Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-warning" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-warning" href="{% url 'blog:post_archive' %}">Archive</a>
                    <a class="dropdown-item text-warning" href="{% url 'blog:search' %}">Search</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search"
                   placeholder="global search" name="search_word">
        </form>
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-light">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-warning" href="#"
                   data-toggle="dropdown">
                    <i class="fas fa-user"></i>
                    {{user.username }} </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-warning"  href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item text-warning" href="{% url 'password_change' %}">
                        Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-warning" href="#"
                   data-toggle="dropdown">
                    <i class="fas fa-user text-warning"></i> Anonymous</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-warning" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item text-warning" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

04_django/webapp/templates/menu2.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
    <a class="navbar-brand" href="#">Logo</a>
    <ul class="navbar-nav">
        <li class="nav-item "><a class="nav-link" href="home1.html"><i class="fas fa-home"></i>Home</a></li>
        <li class="nav-itemv"><a class="nav-link" href="board.html"><i class="fas fa-list"></i>게시판</a></li>
        <li class="nav-item "><a class="nav-link" href="#"><i class="far fa-images"></i>갤러리</a></li>
    </ul>

    <ul class="navbar-nav sticky-top">
        <li class="nav-item "><a class="nav-link" href="login.html"><i
                class="fas fa-sign-in-alt"></i>로그인</a></li>
        <li class="nav-item "><a class="nav-link" href="#"><i
                class="fas fa-user"></i>회원가입</a></li>

    </ul>
</nav>

04_django/webapp/templates/pagination.html
<ul class="pagination mt-5 justify-content-center"">
  {% if page_obj.has_previous %}
  <li class="page-item">
   <a class="page-link" href="?page={{pag_obj.previous_page_number}}">
    <i class="fas fa-angle-double-left"></i></a></i>
   {% endif %}
   {% for page in paginator.page_range %}
   <li class="page-item {%if page == page_obj.number%}active{%endif%}">
 <a class = "page-link" href="?page={{page}}">{{page}}</a></li>

  {% endfor %}
  {% if page_obj.has_next %}
  <li class="page-item">
   <a class="page-link" href="?page={{page_obj.next_page_number}}">
    <i class="fas fa-angle-double-right"></i></a></li>
   {% endif %}
</ul>